# Generated by Django 5.0b1 on 2024-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(auto_now=True)),
                ('price', models.IntegerField()),
                ('account', models.CharField(max_length=150)),
                ('remaining_price', models.CharField(max_length=150)),
            ],
        ),
    ]
