# Generated by Django 5.0b1 on 2024-01-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.payment'),
        ),
    ]
