# Generated by Django 5.0b1 on 2024-01-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_student_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.student'),
        ),
    ]
