# Generated by Django 5.0b1 on 2024-01-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_remove_student_payment_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.CharField(default=6037991784183869, max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='remaining_price',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
