# Generated by Django 5.0b1 on 2024-01-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_payment_remaining_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.IntegerField(blank=True, default=2000000, null=True),
        ),
    ]
