# Generated by Django 5.0b1 on 2024-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
