# Generated by Django 5.0b1 on 2024-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(),
        ),
    ]
