# Generated by Django 5.0b1 on 2024-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_alter_payment_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherterm',
            name='class_number',
            field=models.IntegerField(null=True),
        ),
    ]
