# Generated by Django 5.0 on 2024-01-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_teacherterm_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nat_code',
            field=models.CharField(max_length=150, verbose_name='کد ملی'),
        ),
    ]
