# Generated by Django 5.0 on 2024-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_alter_student_nat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday_date',
            field=models.DateField(verbose_name='تاریخ تولد دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='نام دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='نام خانوادگی دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=150, verbose_name='شماره تلفن همراه دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regdate',
            field=models.DateField(verbose_name='تاریخ ثبت دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(verbose_name='نمره دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=150, verbose_name='شماره تلفن ثابت دانشجو'),
        ),
    ]
