# Generated by Django 5.0 on 2024-01-08 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_alter_student_birthday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.level', verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='regdate',
            field=models.DateField(verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='نام مقطع'),
        ),
        migrations.AlterField(
            model_name='level',
            name='regdate',
            field=models.DateField(null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.CharField(default=6037991784183869, max_length=150, verbose_name='به حساب'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=150, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='remaining_price',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مبلغ مانده'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.IntegerField(blank=True, default=2000000, null=True, verbose_name='مبلغ قابل پرداختت'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='regdate',
            field=models.DateField(verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.term', verbose_name='ترم'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday_date',
            field=models.DateField(verbose_name='تاریخ تولد استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='field',
            field=models.CharField(max_length=150, verbose_name='رشته تحصیلی استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='نام استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='نام خانوادگی استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(max_length=150, verbose_name='شماره تلفن استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nat_code',
            field=models.CharField(max_length=150, verbose_name='کد ملی استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='regdate',
            field=models.DateField(verbose_name='تاریخ ثبت استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(max_length=150, verbose_name='شماره تلفن ثابت استاد'),
        ),
        migrations.AlterField(
            model_name='teacherterm',
            name='class_number',
            field=models.IntegerField(null=True, verbose_name='شماره کلاس'),
        ),
        migrations.AlterField(
            model_name='teacherterm',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='teacherterm',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='teacherterm',
            name='regdate',
            field=models.DateField(verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='teacherterm',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='teacherterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.term', verbose_name='ترم'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='term',
            name='endDate',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام ترم'),
        ),
        migrations.AlterField(
            model_name='term',
            name='regdate',
            field=models.DateField(verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='term',
            name='startDate',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
    ]
