# Generated by Django 5.0 on 2024-01-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_alter_course_description_alter_course_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(verbose_name='تاریخ پرداخت')),
                ('hours', models.IntegerField(verbose_name='ساعت')),
                ('price_in_hour', models.IntegerField(verbose_name='حقوق ساعت')),
                ('total', models.IntegerField(verbose_name='مجموع')),
                ('account', models.CharField(default=6037991784183869, max_length=150, verbose_name='به حساب')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.teacher', verbose_name='استاد')),
            ],
        ),
    ]
