# Generated by Django 5.0 on 2024-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_teacherpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpayment',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='مجموع'),
        ),
    ]
