# Generated by Django 5.0b1 on 2024-01-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_alter_teacherpayment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='college.studentterm'),
            preserve_default=False,
        ),
    ]
